// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: bonanza.build/pkg/proto/model/initialsizeclass/initialsizeclass.proto

package initialsizeclass

import (
	core "bonanza.build/pkg/proto/model/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreviousExecution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*PreviousExecution_Failed
	//	*PreviousExecution_TimedOut
	//	*PreviousExecution_Succeeded
	Outcome       isPreviousExecution_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviousExecution) Reset() {
	*x = PreviousExecution{}
	mi := &file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviousExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviousExecution) ProtoMessage() {}

func (x *PreviousExecution) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviousExecution.ProtoReflect.Descriptor instead.
func (*PreviousExecution) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDescGZIP(), []int{0}
}

func (x *PreviousExecution) GetOutcome() isPreviousExecution_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *PreviousExecution) GetFailed() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Outcome.(*PreviousExecution_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *PreviousExecution) GetTimedOut() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Outcome.(*PreviousExecution_TimedOut); ok {
			return x.TimedOut
		}
	}
	return nil
}

func (x *PreviousExecution) GetSucceeded() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Outcome.(*PreviousExecution_Succeeded); ok {
			return x.Succeeded
		}
	}
	return nil
}

type isPreviousExecution_Outcome interface {
	isPreviousExecution_Outcome()
}

type PreviousExecution_Failed struct {
	Failed *emptypb.Empty `protobuf:"bytes,1,opt,name=failed,proto3,oneof"`
}

type PreviousExecution_TimedOut struct {
	TimedOut *durationpb.Duration `protobuf:"bytes,2,opt,name=timed_out,json=timedOut,proto3,oneof"`
}

type PreviousExecution_Succeeded struct {
	Succeeded *durationpb.Duration `protobuf:"bytes,3,opt,name=succeeded,proto3,oneof"`
}

func (*PreviousExecution_Failed) isPreviousExecution_Outcome() {}

func (*PreviousExecution_TimedOut) isPreviousExecution_Outcome() {}

func (*PreviousExecution_Succeeded) isPreviousExecution_Outcome() {}

type PerSizeClassStats struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	PreviousExecutions         []*PreviousExecution   `protobuf:"bytes,1,rep,name=previous_executions,json=previousExecutions,proto3" json:"previous_executions,omitempty"`
	InitialPageRankProbability float64                `protobuf:"fixed64,2,opt,name=initial_page_rank_probability,json=initialPageRankProbability,proto3" json:"initial_page_rank_probability,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *PerSizeClassStats) Reset() {
	*x = PerSizeClassStats{}
	mi := &file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerSizeClassStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerSizeClassStats) ProtoMessage() {}

func (x *PerSizeClassStats) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerSizeClassStats.ProtoReflect.Descriptor instead.
func (*PerSizeClassStats) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDescGZIP(), []int{1}
}

func (x *PerSizeClassStats) GetPreviousExecutions() []*PreviousExecution {
	if x != nil {
		return x.PreviousExecutions
	}
	return nil
}

func (x *PerSizeClassStats) GetInitialPageRankProbability() float64 {
	if x != nil {
		return x.InitialPageRankProbability
	}
	return 0
}

type PreviousExecutionStats struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	SizeClasses     map[uint32]*PerSizeClassStats `protobuf:"bytes,1,rep,name=size_classes,json=sizeClasses,proto3" json:"size_classes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastSeenFailure *timestamppb.Timestamp        `protobuf:"bytes,2,opt,name=last_seen_failure,json=lastSeenFailure,proto3" json:"last_seen_failure,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreviousExecutionStats) Reset() {
	*x = PreviousExecutionStats{}
	mi := &file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviousExecutionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviousExecutionStats) ProtoMessage() {}

func (x *PreviousExecutionStats) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviousExecutionStats.ProtoReflect.Descriptor instead.
func (*PreviousExecutionStats) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDescGZIP(), []int{2}
}

func (x *PreviousExecutionStats) GetSizeClasses() map[uint32]*PerSizeClassStats {
	if x != nil {
		return x.SizeClasses
	}
	return nil
}

func (x *PreviousExecutionStats) GetLastSeenFailure() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenFailure
	}
	return nil
}

type TagKeyData struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CommonKeyDataReference *core.Reference        `protobuf:"bytes,1,opt,name=common_key_data_reference,json=commonKeyDataReference,proto3" json:"common_key_data_reference,omitempty"`
	PlatformPkixPublicKey  []byte                 `protobuf:"bytes,2,opt,name=platform_pkix_public_key,json=platformPkixPublicKey,proto3" json:"platform_pkix_public_key,omitempty"`
	StableFingerprint      []byte                 `protobuf:"bytes,3,opt,name=stable_fingerprint,json=stableFingerprint,proto3" json:"stable_fingerprint,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TagKeyData) Reset() {
	*x = TagKeyData{}
	mi := &file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagKeyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagKeyData) ProtoMessage() {}

func (x *TagKeyData) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagKeyData.ProtoReflect.Descriptor instead.
func (*TagKeyData) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDescGZIP(), []int{3}
}

func (x *TagKeyData) GetCommonKeyDataReference() *core.Reference {
	if x != nil {
		return x.CommonKeyDataReference
	}
	return nil
}

func (x *TagKeyData) GetPlatformPkixPublicKey() []byte {
	if x != nil {
		return x.PlatformPkixPublicKey
	}
	return nil
}

func (x *TagKeyData) GetStableFingerprint() []byte {
	if x != nil {
		return x.StableFingerprint
	}
	return nil
}

var File_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto protoreflect.FileDescriptor

const file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDesc = "" +
	"\n" +
	"Ebonanza.build/pkg/proto/model/initialsizeclass/initialsizeclass.proto\x12\x1ebonanza.model.initialsizeclass\x1a-bonanza.build/pkg/proto/model/core/core.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x01\n" +
	"\x11PreviousExecution\x120\n" +
	"\x06failed\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x06failed\x128\n" +
	"\ttimed_out\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x00R\btimedOut\x129\n" +
	"\tsucceeded\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x00R\tsucceededB\t\n" +
	"\aoutcome\"\xba\x01\n" +
	"\x11PerSizeClassStats\x12b\n" +
	"\x13previous_executions\x18\x01 \x03(\v21.bonanza.model.initialsizeclass.PreviousExecutionR\x12previousExecutions\x12A\n" +
	"\x1dinitial_page_rank_probability\x18\x02 \x01(\x01R\x1ainitialPageRankProbability\"\xbf\x02\n" +
	"\x16PreviousExecutionStats\x12j\n" +
	"\fsize_classes\x18\x01 \x03(\v2G.bonanza.model.initialsizeclass.PreviousExecutionStats.SizeClassesEntryR\vsizeClasses\x12F\n" +
	"\x11last_seen_failure\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastSeenFailure\x1aq\n" +
	"\x10SizeClassesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12G\n" +
	"\x05value\x18\x02 \x01(\v21.bonanza.model.initialsizeclass.PerSizeClassStatsR\x05value:\x028\x01\"\xce\x01\n" +
	"\n" +
	"TagKeyData\x12X\n" +
	"\x19common_key_data_reference\x18\x01 \x01(\v2\x1d.bonanza.model.core.ReferenceR\x16commonKeyDataReference\x127\n" +
	"\x18platform_pkix_public_key\x18\x02 \x01(\fR\x15platformPkixPublicKey\x12-\n" +
	"\x12stable_fingerprint\x18\x03 \x01(\fR\x11stableFingerprintB0Z.bonanza.build/pkg/proto/model/initialsizeclassb\x06proto3"

var (
	file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDescOnce sync.Once
	file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDescData []byte
)

func file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDescGZIP() []byte {
	file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDescOnce.Do(func() {
		file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDesc), len(file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDesc)))
	})
	return file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDescData
}

var file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_goTypes = []any{
	(*PreviousExecution)(nil),      // 0: bonanza.model.initialsizeclass.PreviousExecution
	(*PerSizeClassStats)(nil),      // 1: bonanza.model.initialsizeclass.PerSizeClassStats
	(*PreviousExecutionStats)(nil), // 2: bonanza.model.initialsizeclass.PreviousExecutionStats
	(*TagKeyData)(nil),             // 3: bonanza.model.initialsizeclass.TagKeyData
	nil,                            // 4: bonanza.model.initialsizeclass.PreviousExecutionStats.SizeClassesEntry
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
	(*durationpb.Duration)(nil),    // 6: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
	(*core.Reference)(nil),         // 8: bonanza.model.core.Reference
}
var file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_depIdxs = []int32{
	5, // 0: bonanza.model.initialsizeclass.PreviousExecution.failed:type_name -> google.protobuf.Empty
	6, // 1: bonanza.model.initialsizeclass.PreviousExecution.timed_out:type_name -> google.protobuf.Duration
	6, // 2: bonanza.model.initialsizeclass.PreviousExecution.succeeded:type_name -> google.protobuf.Duration
	0, // 3: bonanza.model.initialsizeclass.PerSizeClassStats.previous_executions:type_name -> bonanza.model.initialsizeclass.PreviousExecution
	4, // 4: bonanza.model.initialsizeclass.PreviousExecutionStats.size_classes:type_name -> bonanza.model.initialsizeclass.PreviousExecutionStats.SizeClassesEntry
	7, // 5: bonanza.model.initialsizeclass.PreviousExecutionStats.last_seen_failure:type_name -> google.protobuf.Timestamp
	8, // 6: bonanza.model.initialsizeclass.TagKeyData.common_key_data_reference:type_name -> bonanza.model.core.Reference
	1, // 7: bonanza.model.initialsizeclass.PreviousExecutionStats.SizeClassesEntry.value:type_name -> bonanza.model.initialsizeclass.PerSizeClassStats
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_init() }
func file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_init() {
	if File_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto != nil {
		return
	}
	file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_msgTypes[0].OneofWrappers = []any{
		(*PreviousExecution_Failed)(nil),
		(*PreviousExecution_TimedOut)(nil),
		(*PreviousExecution_Succeeded)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDesc), len(file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_goTypes,
		DependencyIndexes: file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_depIdxs,
		MessageInfos:      file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_msgTypes,
	}.Build()
	File_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto = out.File
	file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_goTypes = nil
	file_bonanza_build_pkg_proto_model_initialsizeclass_initialsizeclass_proto_depIdxs = nil
}
