// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: bonanza.build/pkg/proto/configuration/bonanza_browser/bonanza_browser.proto

package bonanza_browser

import (
	parser "bonanza.build/pkg/proto/configuration/model/parser"
	local "bonanza.build/pkg/proto/configuration/storage/object/local"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	server "github.com/buildbarn/bb-storage/pkg/proto/configuration/http/server"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                     protoimpl.MessageState    `protogen:"open.v1"`
	Global                    *global.Configuration     `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	HttpServers               []*server.Configuration   `protobuf:"bytes,2,rep,name=http_servers,json=httpServers,proto3" json:"http_servers,omitempty"`
	StorageGrpcClient         *grpc.ClientConfiguration `protobuf:"bytes,3,opt,name=storage_grpc_client,json=storageGrpcClient,proto3" json:"storage_grpc_client,omitempty"`
	LocalObjectStore          *local.StoreConfiguration `protobuf:"bytes,6,opt,name=local_object_store,json=localObjectStore,proto3" json:"local_object_store,omitempty"`
	ParsedObjectPool          *parser.ParsedObjectPool  `protobuf:"bytes,4,opt,name=parsed_object_pool,json=parsedObjectPool,proto3" json:"parsed_object_pool,omitempty"`
	BuildQueueStateGrpcClient *grpc.ClientConfiguration `protobuf:"bytes,5,opt,name=build_queue_state_grpc_client,json=buildQueueStateGrpcClient,proto3" json:"build_queue_state_grpc_client,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetHttpServers() []*server.Configuration {
	if x != nil {
		return x.HttpServers
	}
	return nil
}

func (x *ApplicationConfiguration) GetStorageGrpcClient() *grpc.ClientConfiguration {
	if x != nil {
		return x.StorageGrpcClient
	}
	return nil
}

func (x *ApplicationConfiguration) GetLocalObjectStore() *local.StoreConfiguration {
	if x != nil {
		return x.LocalObjectStore
	}
	return nil
}

func (x *ApplicationConfiguration) GetParsedObjectPool() *parser.ParsedObjectPool {
	if x != nil {
		return x.ParsedObjectPool
	}
	return nil
}

func (x *ApplicationConfiguration) GetBuildQueueStateGrpcClient() *grpc.ClientConfiguration {
	if x != nil {
		return x.BuildQueueStateGrpcClient
	}
	return nil
}

var File_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto protoreflect.FileDescriptor

const file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_rawDesc = "" +
	"\n" +
	"Kbonanza.build/pkg/proto/configuration/bonanza_browser/bonanza_browser.proto\x12%bonanza.configuration.bonanza_browser\x1a?bonanza.build/pkg/proto/configuration/model/parser/parser.proto\x1aFbonanza.build/pkg/proto/configuration/storage/object/local/local.proto\x1aKgithub.com/buildbarn/bb-storage/pkg/proto/configuration/global/global.proto\x1aGgithub.com/buildbarn/bb-storage/pkg/proto/configuration/grpc/grpc.proto\x1aPgithub.com/buildbarn/bb-storage/pkg/proto/configuration/http/server/server.proto\"\xe2\x04\n" +
	"\x18ApplicationConfiguration\x12E\n" +
	"\x06global\x18\x01 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12U\n" +
	"\fhttp_servers\x18\x02 \x03(\v22.buildbarn.configuration.http.server.ConfigurationR\vhttpServers\x12a\n" +
	"\x13storage_grpc_client\x18\x03 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\x11storageGrpcClient\x12l\n" +
	"\x12local_object_store\x18\x06 \x01(\v2>.bonanza.configuration.storage.object.local.StoreConfigurationR\x10localObjectStore\x12b\n" +
	"\x12parsed_object_pool\x18\x04 \x01(\v24.bonanza.configuration.model.parser.ParsedObjectPoolR\x10parsedObjectPool\x12s\n" +
	"\x1dbuild_queue_state_grpc_client\x18\x05 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\x19buildQueueStateGrpcClientB7Z5bonanza.build/pkg/proto/configuration/bonanza_browserb\x06proto3"

var (
	file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_rawDescOnce sync.Once
	file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_rawDescData []byte
)

func file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_rawDescGZIP() []byte {
	file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_rawDescOnce.Do(func() {
		file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_rawDesc), len(file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_rawDesc)))
	})
	return file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_rawDescData
}

var file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil), // 0: bonanza.configuration.bonanza_browser.ApplicationConfiguration
	(*global.Configuration)(nil),     // 1: buildbarn.configuration.global.Configuration
	(*server.Configuration)(nil),     // 2: buildbarn.configuration.http.server.Configuration
	(*grpc.ClientConfiguration)(nil), // 3: buildbarn.configuration.grpc.ClientConfiguration
	(*local.StoreConfiguration)(nil), // 4: bonanza.configuration.storage.object.local.StoreConfiguration
	(*parser.ParsedObjectPool)(nil),  // 5: bonanza.configuration.model.parser.ParsedObjectPool
}
var file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_depIdxs = []int32{
	1, // 0: bonanza.configuration.bonanza_browser.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	2, // 1: bonanza.configuration.bonanza_browser.ApplicationConfiguration.http_servers:type_name -> buildbarn.configuration.http.server.Configuration
	3, // 2: bonanza.configuration.bonanza_browser.ApplicationConfiguration.storage_grpc_client:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	4, // 3: bonanza.configuration.bonanza_browser.ApplicationConfiguration.local_object_store:type_name -> bonanza.configuration.storage.object.local.StoreConfiguration
	5, // 4: bonanza.configuration.bonanza_browser.ApplicationConfiguration.parsed_object_pool:type_name -> bonanza.configuration.model.parser.ParsedObjectPool
	3, // 5: bonanza.configuration.bonanza_browser.ApplicationConfiguration.build_queue_state_grpc_client:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_init() }
func file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_init() {
	if File_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_rawDesc), len(file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_goTypes,
		DependencyIndexes: file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_depIdxs,
		MessageInfos:      file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_msgTypes,
	}.Build()
	File_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto = out.File
	file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_goTypes = nil
	file_bonanza_build_pkg_proto_configuration_bonanza_browser_bonanza_browser_proto_depIdxs = nil
}
