// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: bonanza.build/pkg/proto/configuration/scheduler/scheduler.proto

package scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionRouterConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ActionRouterConfiguration_Simple
	Kind          isActionRouterConfiguration_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRouterConfiguration) Reset() {
	*x = ActionRouterConfiguration{}
	mi := &file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRouterConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRouterConfiguration) ProtoMessage() {}

func (x *ActionRouterConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRouterConfiguration.ProtoReflect.Descriptor instead.
func (*ActionRouterConfiguration) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ActionRouterConfiguration) GetKind() isActionRouterConfiguration_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ActionRouterConfiguration) GetSimple() *SimpleActionRouterConfiguration {
	if x != nil {
		if x, ok := x.Kind.(*ActionRouterConfiguration_Simple); ok {
			return x.Simple
		}
	}
	return nil
}

type isActionRouterConfiguration_Kind interface {
	isActionRouterConfiguration_Kind()
}

type ActionRouterConfiguration_Simple struct {
	Simple *SimpleActionRouterConfiguration `protobuf:"bytes,1,opt,name=simple,proto3,oneof"`
}

func (*ActionRouterConfiguration_Simple) isActionRouterConfiguration_Kind() {}

type SimpleActionRouterConfiguration struct {
	state                    protoimpl.MessageState                 `protogen:"open.v1"`
	InvocationKeyExtractors  []*InvocationKeyExtractorConfiguration `protobuf:"bytes,1,rep,name=invocation_key_extractors,json=invocationKeyExtractors,proto3" json:"invocation_key_extractors,omitempty"`
	InitialSizeClassAnalyzer *InitialSizeClassAnalyzerConfiguration `protobuf:"bytes,2,opt,name=initial_size_class_analyzer,json=initialSizeClassAnalyzer,proto3" json:"initial_size_class_analyzer,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SimpleActionRouterConfiguration) Reset() {
	*x = SimpleActionRouterConfiguration{}
	mi := &file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleActionRouterConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleActionRouterConfiguration) ProtoMessage() {}

func (x *SimpleActionRouterConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleActionRouterConfiguration.ProtoReflect.Descriptor instead.
func (*SimpleActionRouterConfiguration) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleActionRouterConfiguration) GetInvocationKeyExtractors() []*InvocationKeyExtractorConfiguration {
	if x != nil {
		return x.InvocationKeyExtractors
	}
	return nil
}

func (x *SimpleActionRouterConfiguration) GetInitialSizeClassAnalyzer() *InitialSizeClassAnalyzerConfiguration {
	if x != nil {
		return x.InitialSizeClassAnalyzer
	}
	return nil
}

type InvocationKeyExtractorConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*InvocationKeyExtractorConfiguration_AuthenticationMetadata
	Kind          isInvocationKeyExtractorConfiguration_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationKeyExtractorConfiguration) Reset() {
	*x = InvocationKeyExtractorConfiguration{}
	mi := &file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationKeyExtractorConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationKeyExtractorConfiguration) ProtoMessage() {}

func (x *InvocationKeyExtractorConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationKeyExtractorConfiguration.ProtoReflect.Descriptor instead.
func (*InvocationKeyExtractorConfiguration) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *InvocationKeyExtractorConfiguration) GetKind() isInvocationKeyExtractorConfiguration_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *InvocationKeyExtractorConfiguration) GetAuthenticationMetadata() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Kind.(*InvocationKeyExtractorConfiguration_AuthenticationMetadata); ok {
			return x.AuthenticationMetadata
		}
	}
	return nil
}

type isInvocationKeyExtractorConfiguration_Kind interface {
	isInvocationKeyExtractorConfiguration_Kind()
}

type InvocationKeyExtractorConfiguration_AuthenticationMetadata struct {
	AuthenticationMetadata *emptypb.Empty `protobuf:"bytes,1,opt,name=authentication_metadata,json=authenticationMetadata,proto3,oneof"`
}

func (*InvocationKeyExtractorConfiguration_AuthenticationMetadata) isInvocationKeyExtractorConfiguration_Kind() {
}

type InitialSizeClassAnalyzerConfiguration struct {
	state                   protoimpl.MessageState                               `protogen:"open.v1"`
	MaximumExecutionTimeout *durationpb.Duration                                 `protobuf:"bytes,1,opt,name=maximum_execution_timeout,json=maximumExecutionTimeout,proto3" json:"maximum_execution_timeout,omitempty"`
	FeedbackDriven          *InitialSizeClassFeedbackDrivenAnalyzerConfiguration `protobuf:"bytes,2,opt,name=feedback_driven,json=feedbackDriven,proto3" json:"feedback_driven,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *InitialSizeClassAnalyzerConfiguration) Reset() {
	*x = InitialSizeClassAnalyzerConfiguration{}
	mi := &file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialSizeClassAnalyzerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSizeClassAnalyzerConfiguration) ProtoMessage() {}

func (x *InitialSizeClassAnalyzerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSizeClassAnalyzerConfiguration.ProtoReflect.Descriptor instead.
func (*InitialSizeClassAnalyzerConfiguration) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *InitialSizeClassAnalyzerConfiguration) GetMaximumExecutionTimeout() *durationpb.Duration {
	if x != nil {
		return x.MaximumExecutionTimeout
	}
	return nil
}

func (x *InitialSizeClassAnalyzerConfiguration) GetFeedbackDriven() *InitialSizeClassFeedbackDrivenAnalyzerConfiguration {
	if x != nil {
		return x.FeedbackDriven
	}
	return nil
}

type InitialSizeClassFeedbackDrivenAnalyzerConfiguration struct {
	state                protoimpl.MessageState                                   `protogen:"open.v1"`
	FailureCacheDuration *durationpb.Duration                                     `protobuf:"bytes,1,opt,name=failure_cache_duration,json=failureCacheDuration,proto3" json:"failure_cache_duration,omitempty"`
	HistorySize          int32                                                    `protobuf:"varint,2,opt,name=history_size,json=historySize,proto3" json:"history_size,omitempty"`
	PageRank             *InitialSizeClassPageRankStrategyCalculatorConfiguration `protobuf:"bytes,3,opt,name=page_rank,json=pageRank,proto3" json:"page_rank,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InitialSizeClassFeedbackDrivenAnalyzerConfiguration) Reset() {
	*x = InitialSizeClassFeedbackDrivenAnalyzerConfiguration{}
	mi := &file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialSizeClassFeedbackDrivenAnalyzerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSizeClassFeedbackDrivenAnalyzerConfiguration) ProtoMessage() {}

func (x *InitialSizeClassFeedbackDrivenAnalyzerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSizeClassFeedbackDrivenAnalyzerConfiguration.ProtoReflect.Descriptor instead.
func (*InitialSizeClassFeedbackDrivenAnalyzerConfiguration) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *InitialSizeClassFeedbackDrivenAnalyzerConfiguration) GetFailureCacheDuration() *durationpb.Duration {
	if x != nil {
		return x.FailureCacheDuration
	}
	return nil
}

func (x *InitialSizeClassFeedbackDrivenAnalyzerConfiguration) GetHistorySize() int32 {
	if x != nil {
		return x.HistorySize
	}
	return 0
}

func (x *InitialSizeClassFeedbackDrivenAnalyzerConfiguration) GetPageRank() *InitialSizeClassPageRankStrategyCalculatorConfiguration {
	if x != nil {
		return x.PageRank
	}
	return nil
}

type InitialSizeClassPageRankStrategyCalculatorConfiguration struct {
	state                                      protoimpl.MessageState `protogen:"open.v1"`
	AcceptableExecutionTimeIncreaseExponent    float64                `protobuf:"fixed64,1,opt,name=acceptable_execution_time_increase_exponent,json=acceptableExecutionTimeIncreaseExponent,proto3" json:"acceptable_execution_time_increase_exponent,omitempty"`
	SmallerSizeClassExecutionTimeoutMultiplier float64                `protobuf:"fixed64,2,opt,name=smaller_size_class_execution_timeout_multiplier,json=smallerSizeClassExecutionTimeoutMultiplier,proto3" json:"smaller_size_class_execution_timeout_multiplier,omitempty"`
	MinimumExecutionTimeout                    *durationpb.Duration   `protobuf:"bytes,3,opt,name=minimum_execution_timeout,json=minimumExecutionTimeout,proto3" json:"minimum_execution_timeout,omitempty"`
	MaximumConvergenceError                    float64                `protobuf:"fixed64,4,opt,name=maximum_convergence_error,json=maximumConvergenceError,proto3" json:"maximum_convergence_error,omitempty"`
	unknownFields                              protoimpl.UnknownFields
	sizeCache                                  protoimpl.SizeCache
}

func (x *InitialSizeClassPageRankStrategyCalculatorConfiguration) Reset() {
	*x = InitialSizeClassPageRankStrategyCalculatorConfiguration{}
	mi := &file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialSizeClassPageRankStrategyCalculatorConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSizeClassPageRankStrategyCalculatorConfiguration) ProtoMessage() {}

func (x *InitialSizeClassPageRankStrategyCalculatorConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSizeClassPageRankStrategyCalculatorConfiguration.ProtoReflect.Descriptor instead.
func (*InitialSizeClassPageRankStrategyCalculatorConfiguration) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *InitialSizeClassPageRankStrategyCalculatorConfiguration) GetAcceptableExecutionTimeIncreaseExponent() float64 {
	if x != nil {
		return x.AcceptableExecutionTimeIncreaseExponent
	}
	return 0
}

func (x *InitialSizeClassPageRankStrategyCalculatorConfiguration) GetSmallerSizeClassExecutionTimeoutMultiplier() float64 {
	if x != nil {
		return x.SmallerSizeClassExecutionTimeoutMultiplier
	}
	return 0
}

func (x *InitialSizeClassPageRankStrategyCalculatorConfiguration) GetMinimumExecutionTimeout() *durationpb.Duration {
	if x != nil {
		return x.MinimumExecutionTimeout
	}
	return nil
}

func (x *InitialSizeClassPageRankStrategyCalculatorConfiguration) GetMaximumConvergenceError() float64 {
	if x != nil {
		return x.MaximumConvergenceError
	}
	return 0
}

var File_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto protoreflect.FileDescriptor

const file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDesc = "" +
	"\n" +
	"?bonanza.build/pkg/proto/configuration/scheduler/scheduler.proto\x12\x1fbonanza.configuration.scheduler\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x7f\n" +
	"\x19ActionRouterConfiguration\x12Z\n" +
	"\x06simple\x18\x01 \x01(\v2@.bonanza.configuration.scheduler.SimpleActionRouterConfigurationH\x00R\x06simpleB\x06\n" +
	"\x04kind\"\xac\x02\n" +
	"\x1fSimpleActionRouterConfiguration\x12\x80\x01\n" +
	"\x19invocation_key_extractors\x18\x01 \x03(\v2D.bonanza.configuration.scheduler.InvocationKeyExtractorConfigurationR\x17invocationKeyExtractors\x12\x85\x01\n" +
	"\x1binitial_size_class_analyzer\x18\x02 \x01(\v2F.bonanza.configuration.scheduler.InitialSizeClassAnalyzerConfigurationR\x18initialSizeClassAnalyzer\"\x80\x01\n" +
	"#InvocationKeyExtractorConfiguration\x12Q\n" +
	"\x17authentication_metadata\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x16authenticationMetadataB\x06\n" +
	"\x04kind\"\xfd\x01\n" +
	"%InitialSizeClassAnalyzerConfiguration\x12U\n" +
	"\x19maximum_execution_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x17maximumExecutionTimeout\x12}\n" +
	"\x0ffeedback_driven\x18\x02 \x01(\v2T.bonanza.configuration.scheduler.InitialSizeClassFeedbackDrivenAnalyzerConfigurationR\x0efeedbackDriven\"\xa0\x02\n" +
	"3InitialSizeClassFeedbackDrivenAnalyzerConfiguration\x12O\n" +
	"\x16failure_cache_duration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x14failureCacheDuration\x12!\n" +
	"\fhistory_size\x18\x02 \x01(\x05R\vhistorySize\x12u\n" +
	"\tpage_rank\x18\x03 \x01(\v2X.bonanza.configuration.scheduler.InitialSizeClassPageRankStrategyCalculatorConfigurationR\bpageRank\"\x8f\x03\n" +
	"7InitialSizeClassPageRankStrategyCalculatorConfiguration\x12\\\n" +
	"+acceptable_execution_time_increase_exponent\x18\x01 \x01(\x01R'acceptableExecutionTimeIncreaseExponent\x12c\n" +
	"/smaller_size_class_execution_timeout_multiplier\x18\x02 \x01(\x01R*smallerSizeClassExecutionTimeoutMultiplier\x12U\n" +
	"\x19minimum_execution_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x17minimumExecutionTimeout\x12:\n" +
	"\x19maximum_convergence_error\x18\x04 \x01(\x01R\x17maximumConvergenceErrorB1Z/bonanza.build/pkg/proto/configuration/schedulerb\x06proto3"

var (
	file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDescOnce sync.Once
	file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDescData []byte
)

func file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDescGZIP() []byte {
	file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDescOnce.Do(func() {
		file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDesc), len(file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDesc)))
	})
	return file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDescData
}

var file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_goTypes = []any{
	(*ActionRouterConfiguration)(nil),                               // 0: bonanza.configuration.scheduler.ActionRouterConfiguration
	(*SimpleActionRouterConfiguration)(nil),                         // 1: bonanza.configuration.scheduler.SimpleActionRouterConfiguration
	(*InvocationKeyExtractorConfiguration)(nil),                     // 2: bonanza.configuration.scheduler.InvocationKeyExtractorConfiguration
	(*InitialSizeClassAnalyzerConfiguration)(nil),                   // 3: bonanza.configuration.scheduler.InitialSizeClassAnalyzerConfiguration
	(*InitialSizeClassFeedbackDrivenAnalyzerConfiguration)(nil),     // 4: bonanza.configuration.scheduler.InitialSizeClassFeedbackDrivenAnalyzerConfiguration
	(*InitialSizeClassPageRankStrategyCalculatorConfiguration)(nil), // 5: bonanza.configuration.scheduler.InitialSizeClassPageRankStrategyCalculatorConfiguration
	(*emptypb.Empty)(nil),                                           // 6: google.protobuf.Empty
	(*durationpb.Duration)(nil),                                     // 7: google.protobuf.Duration
}
var file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_depIdxs = []int32{
	1, // 0: bonanza.configuration.scheduler.ActionRouterConfiguration.simple:type_name -> bonanza.configuration.scheduler.SimpleActionRouterConfiguration
	2, // 1: bonanza.configuration.scheduler.SimpleActionRouterConfiguration.invocation_key_extractors:type_name -> bonanza.configuration.scheduler.InvocationKeyExtractorConfiguration
	3, // 2: bonanza.configuration.scheduler.SimpleActionRouterConfiguration.initial_size_class_analyzer:type_name -> bonanza.configuration.scheduler.InitialSizeClassAnalyzerConfiguration
	6, // 3: bonanza.configuration.scheduler.InvocationKeyExtractorConfiguration.authentication_metadata:type_name -> google.protobuf.Empty
	7, // 4: bonanza.configuration.scheduler.InitialSizeClassAnalyzerConfiguration.maximum_execution_timeout:type_name -> google.protobuf.Duration
	4, // 5: bonanza.configuration.scheduler.InitialSizeClassAnalyzerConfiguration.feedback_driven:type_name -> bonanza.configuration.scheduler.InitialSizeClassFeedbackDrivenAnalyzerConfiguration
	7, // 6: bonanza.configuration.scheduler.InitialSizeClassFeedbackDrivenAnalyzerConfiguration.failure_cache_duration:type_name -> google.protobuf.Duration
	5, // 7: bonanza.configuration.scheduler.InitialSizeClassFeedbackDrivenAnalyzerConfiguration.page_rank:type_name -> bonanza.configuration.scheduler.InitialSizeClassPageRankStrategyCalculatorConfiguration
	7, // 8: bonanza.configuration.scheduler.InitialSizeClassPageRankStrategyCalculatorConfiguration.minimum_execution_timeout:type_name -> google.protobuf.Duration
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_init() }
func file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_init() {
	if File_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto != nil {
		return
	}
	file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[0].OneofWrappers = []any{
		(*ActionRouterConfiguration_Simple)(nil),
	}
	file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes[2].OneofWrappers = []any{
		(*InvocationKeyExtractorConfiguration_AuthenticationMetadata)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDesc), len(file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_goTypes,
		DependencyIndexes: file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_depIdxs,
		MessageInfos:      file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_msgTypes,
	}.Build()
	File_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto = out.File
	file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_goTypes = nil
	file_bonanza_build_pkg_proto_configuration_scheduler_scheduler_proto_depIdxs = nil
}
