// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: bonanza.build/pkg/proto/configuration/storage/object/local/local.proto

package local

import (
	lossymap "bonanza.build/pkg/proto/configuration/ds/lossymap"
	blockdevice "github.com/buildbarn/bb-storage/pkg/proto/configuration/blockdevice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreConfiguration struct {
	state                protoimpl.MessageState         `protogen:"open.v1"`
	ReferenceLocationMap *lossymap.HashMapConfiguration `protobuf:"bytes,1,opt,name=reference_location_map,json=referenceLocationMap,proto3" json:"reference_location_map,omitempty"`
	// Types that are valid to be assigned to LocationBlobMapBackend:
	//
	//	*StoreConfiguration_LocationBlobMapInMemory_
	//	*StoreConfiguration_LocationBlobMapOnBlockDevice
	LocationBlobMapBackend isStoreConfiguration_LocationBlobMapBackend `protobuf_oneof:"location_blob_map_backend"`
	OldRegionSizeRatio     uint32                                      `protobuf:"varint,4,opt,name=old_region_size_ratio,json=oldRegionSizeRatio,proto3" json:"old_region_size_ratio,omitempty"`
	CurrentRegionSizeRatio uint32                                      `protobuf:"varint,5,opt,name=current_region_size_ratio,json=currentRegionSizeRatio,proto3" json:"current_region_size_ratio,omitempty"`
	NewRegionSizeRatio     uint32                                      `protobuf:"varint,6,opt,name=new_region_size_ratio,json=newRegionSizeRatio,proto3" json:"new_region_size_ratio,omitempty"`
	Persistent             *StoreConfiguration_Persistent              `protobuf:"bytes,7,opt,name=persistent,proto3" json:"persistent,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StoreConfiguration) Reset() {
	*x = StoreConfiguration{}
	mi := &file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreConfiguration) ProtoMessage() {}

func (x *StoreConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreConfiguration.ProtoReflect.Descriptor instead.
func (*StoreConfiguration) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDescGZIP(), []int{0}
}

func (x *StoreConfiguration) GetReferenceLocationMap() *lossymap.HashMapConfiguration {
	if x != nil {
		return x.ReferenceLocationMap
	}
	return nil
}

func (x *StoreConfiguration) GetLocationBlobMapBackend() isStoreConfiguration_LocationBlobMapBackend {
	if x != nil {
		return x.LocationBlobMapBackend
	}
	return nil
}

func (x *StoreConfiguration) GetLocationBlobMapInMemory() *StoreConfiguration_LocationBlobMapInMemory {
	if x != nil {
		if x, ok := x.LocationBlobMapBackend.(*StoreConfiguration_LocationBlobMapInMemory_); ok {
			return x.LocationBlobMapInMemory
		}
	}
	return nil
}

func (x *StoreConfiguration) GetLocationBlobMapOnBlockDevice() *blockdevice.Configuration {
	if x != nil {
		if x, ok := x.LocationBlobMapBackend.(*StoreConfiguration_LocationBlobMapOnBlockDevice); ok {
			return x.LocationBlobMapOnBlockDevice
		}
	}
	return nil
}

func (x *StoreConfiguration) GetOldRegionSizeRatio() uint32 {
	if x != nil {
		return x.OldRegionSizeRatio
	}
	return 0
}

func (x *StoreConfiguration) GetCurrentRegionSizeRatio() uint32 {
	if x != nil {
		return x.CurrentRegionSizeRatio
	}
	return 0
}

func (x *StoreConfiguration) GetNewRegionSizeRatio() uint32 {
	if x != nil {
		return x.NewRegionSizeRatio
	}
	return 0
}

func (x *StoreConfiguration) GetPersistent() *StoreConfiguration_Persistent {
	if x != nil {
		return x.Persistent
	}
	return nil
}

type isStoreConfiguration_LocationBlobMapBackend interface {
	isStoreConfiguration_LocationBlobMapBackend()
}

type StoreConfiguration_LocationBlobMapInMemory_ struct {
	LocationBlobMapInMemory *StoreConfiguration_LocationBlobMapInMemory `protobuf:"bytes,2,opt,name=location_blob_map_in_memory,json=locationBlobMapInMemory,proto3,oneof"`
}

type StoreConfiguration_LocationBlobMapOnBlockDevice struct {
	LocationBlobMapOnBlockDevice *blockdevice.Configuration `protobuf:"bytes,3,opt,name=location_blob_map_on_block_device,json=locationBlobMapOnBlockDevice,proto3,oneof"`
}

func (*StoreConfiguration_LocationBlobMapInMemory_) isStoreConfiguration_LocationBlobMapBackend() {}

func (*StoreConfiguration_LocationBlobMapOnBlockDevice) isStoreConfiguration_LocationBlobMapBackend() {
}

type StoreConfiguration_LocationBlobMapInMemory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeBytes     uint64                 `protobuf:"varint,1,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreConfiguration_LocationBlobMapInMemory) Reset() {
	*x = StoreConfiguration_LocationBlobMapInMemory{}
	mi := &file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreConfiguration_LocationBlobMapInMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreConfiguration_LocationBlobMapInMemory) ProtoMessage() {}

func (x *StoreConfiguration_LocationBlobMapInMemory) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreConfiguration_LocationBlobMapInMemory.ProtoReflect.Descriptor instead.
func (*StoreConfiguration_LocationBlobMapInMemory) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDescGZIP(), []int{0, 0}
}

func (x *StoreConfiguration_LocationBlobMapInMemory) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type StoreConfiguration_Persistent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	StateDirectoryPath   string                 `protobuf:"bytes,1,opt,name=state_directory_path,json=stateDirectoryPath,proto3" json:"state_directory_path,omitempty"`
	MinimumEpochInterval *durationpb.Duration   `protobuf:"bytes,2,opt,name=minimum_epoch_interval,json=minimumEpochInterval,proto3" json:"minimum_epoch_interval,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StoreConfiguration_Persistent) Reset() {
	*x = StoreConfiguration_Persistent{}
	mi := &file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreConfiguration_Persistent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreConfiguration_Persistent) ProtoMessage() {}

func (x *StoreConfiguration_Persistent) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreConfiguration_Persistent.ProtoReflect.Descriptor instead.
func (*StoreConfiguration_Persistent) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDescGZIP(), []int{0, 1}
}

func (x *StoreConfiguration_Persistent) GetStateDirectoryPath() string {
	if x != nil {
		return x.StateDirectoryPath
	}
	return ""
}

func (x *StoreConfiguration_Persistent) GetMinimumEpochInterval() *durationpb.Duration {
	if x != nil {
		return x.MinimumEpochInterval
	}
	return nil
}

var File_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto protoreflect.FileDescriptor

const file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDesc = "" +
	"\n" +
	"Fbonanza.build/pkg/proto/configuration/storage/object/local/local.proto\x12*bonanza.configuration.storage.object.local\x1a@bonanza.build/pkg/proto/configuration/ds/lossymap/lossymap.proto\x1aUgithub.com/buildbarn/bb-storage/pkg/proto/configuration/blockdevice/blockdevice.proto\x1a\x1egoogle/protobuf/duration.proto\"\x90\a\n" +
	"\x12StoreConfiguration\x12m\n" +
	"\x16reference_location_map\x18\x01 \x01(\v27.bonanza.configuration.ds.lossymap.HashMapConfigurationR\x14referenceLocationMap\x12\x96\x01\n" +
	"\x1blocation_blob_map_in_memory\x18\x02 \x01(\v2V.bonanza.configuration.storage.object.local.StoreConfiguration.LocationBlobMapInMemoryH\x00R\x17locationBlobMapInMemory\x12}\n" +
	"!location_blob_map_on_block_device\x18\x03 \x01(\v22.buildbarn.configuration.blockdevice.ConfigurationH\x00R\x1clocationBlobMapOnBlockDevice\x121\n" +
	"\x15old_region_size_ratio\x18\x04 \x01(\rR\x12oldRegionSizeRatio\x129\n" +
	"\x19current_region_size_ratio\x18\x05 \x01(\rR\x16currentRegionSizeRatio\x121\n" +
	"\x15new_region_size_ratio\x18\x06 \x01(\rR\x12newRegionSizeRatio\x12i\n" +
	"\n" +
	"persistent\x18\a \x01(\v2I.bonanza.configuration.storage.object.local.StoreConfiguration.PersistentR\n" +
	"persistent\x1a8\n" +
	"\x17LocationBlobMapInMemory\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x01 \x01(\x04R\tsizeBytes\x1a\x8f\x01\n" +
	"\n" +
	"Persistent\x120\n" +
	"\x14state_directory_path\x18\x01 \x01(\tR\x12stateDirectoryPath\x12O\n" +
	"\x16minimum_epoch_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x14minimumEpochIntervalB\x1b\n" +
	"\x19location_blob_map_backendB<Z:bonanza.build/pkg/proto/configuration/storage/object/localb\x06proto3"

var (
	file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDescOnce sync.Once
	file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDescData []byte
)

func file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDescGZIP() []byte {
	file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDescOnce.Do(func() {
		file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDesc), len(file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDesc)))
	})
	return file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDescData
}

var file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_goTypes = []any{
	(*StoreConfiguration)(nil),                         // 0: bonanza.configuration.storage.object.local.StoreConfiguration
	(*StoreConfiguration_LocationBlobMapInMemory)(nil), // 1: bonanza.configuration.storage.object.local.StoreConfiguration.LocationBlobMapInMemory
	(*StoreConfiguration_Persistent)(nil),              // 2: bonanza.configuration.storage.object.local.StoreConfiguration.Persistent
	(*lossymap.HashMapConfiguration)(nil),              // 3: bonanza.configuration.ds.lossymap.HashMapConfiguration
	(*blockdevice.Configuration)(nil),                  // 4: buildbarn.configuration.blockdevice.Configuration
	(*durationpb.Duration)(nil),                        // 5: google.protobuf.Duration
}
var file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_depIdxs = []int32{
	3, // 0: bonanza.configuration.storage.object.local.StoreConfiguration.reference_location_map:type_name -> bonanza.configuration.ds.lossymap.HashMapConfiguration
	1, // 1: bonanza.configuration.storage.object.local.StoreConfiguration.location_blob_map_in_memory:type_name -> bonanza.configuration.storage.object.local.StoreConfiguration.LocationBlobMapInMemory
	4, // 2: bonanza.configuration.storage.object.local.StoreConfiguration.location_blob_map_on_block_device:type_name -> buildbarn.configuration.blockdevice.Configuration
	2, // 3: bonanza.configuration.storage.object.local.StoreConfiguration.persistent:type_name -> bonanza.configuration.storage.object.local.StoreConfiguration.Persistent
	5, // 4: bonanza.configuration.storage.object.local.StoreConfiguration.Persistent.minimum_epoch_interval:type_name -> google.protobuf.Duration
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_init() }
func file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_init() {
	if File_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto != nil {
		return
	}
	file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_msgTypes[0].OneofWrappers = []any{
		(*StoreConfiguration_LocationBlobMapInMemory_)(nil),
		(*StoreConfiguration_LocationBlobMapOnBlockDevice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDesc), len(file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_goTypes,
		DependencyIndexes: file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_depIdxs,
		MessageInfos:      file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_msgTypes,
	}.Build()
	File_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto = out.File
	file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_goTypes = nil
	file_bonanza_build_pkg_proto_configuration_storage_object_local_local_proto_depIdxs = nil
}
