// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: bonanza.build/pkg/proto/model/tag/tag.proto

package tag

import (
	encoding "bonanza.build/pkg/proto/model/encoding"
	object "bonanza.build/pkg/proto/storage/object"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonKeyData struct {
	state              protoimpl.MessageState       `protogen:"open.v1"`
	SignaturePublicKey []byte                       `protobuf:"bytes,1,opt,name=signature_public_key,json=signaturePublicKey,proto3" json:"signature_public_key,omitempty"`
	ReferenceFormat    object.ReferenceFormat_Value `protobuf:"varint,2,opt,name=reference_format,json=referenceFormat,proto3,enum=bonanza.storage.object.ReferenceFormat_Value" json:"reference_format,omitempty"`
	ObjectEncoders     []*encoding.BinaryEncoder    `protobuf:"bytes,3,rep,name=object_encoders,json=objectEncoders,proto3" json:"object_encoders,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CommonKeyData) Reset() {
	*x = CommonKeyData{}
	mi := &file_bonanza_build_pkg_proto_model_tag_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonKeyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonKeyData) ProtoMessage() {}

func (x *CommonKeyData) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_model_tag_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonKeyData.ProtoReflect.Descriptor instead.
func (*CommonKeyData) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_model_tag_tag_proto_rawDescGZIP(), []int{0}
}

func (x *CommonKeyData) GetSignaturePublicKey() []byte {
	if x != nil {
		return x.SignaturePublicKey
	}
	return nil
}

func (x *CommonKeyData) GetReferenceFormat() object.ReferenceFormat_Value {
	if x != nil {
		return x.ReferenceFormat
	}
	return object.ReferenceFormat_Value(0)
}

func (x *CommonKeyData) GetObjectEncoders() []*encoding.BinaryEncoder {
	if x != nil {
		return x.ObjectEncoders
	}
	return nil
}

var File_bonanza_build_pkg_proto_model_tag_tag_proto protoreflect.FileDescriptor

const file_bonanza_build_pkg_proto_model_tag_tag_proto_rawDesc = "" +
	"\n" +
	"+bonanza.build/pkg/proto/model/tag/tag.proto\x12\x11bonanza.model.tag\x1a5bonanza.build/pkg/proto/model/encoding/encoding.proto\x1a3bonanza.build/pkg/proto/storage/object/object.proto\"\xeb\x01\n" +
	"\rCommonKeyData\x120\n" +
	"\x14signature_public_key\x18\x01 \x01(\fR\x12signaturePublicKey\x12X\n" +
	"\x10reference_format\x18\x02 \x01(\x0e2-.bonanza.storage.object.ReferenceFormat.ValueR\x0freferenceFormat\x12N\n" +
	"\x0fobject_encoders\x18\x03 \x03(\v2%.bonanza.model.encoding.BinaryEncoderR\x0eobjectEncodersB#Z!bonanza.build/pkg/proto/model/tagb\x06proto3"

var (
	file_bonanza_build_pkg_proto_model_tag_tag_proto_rawDescOnce sync.Once
	file_bonanza_build_pkg_proto_model_tag_tag_proto_rawDescData []byte
)

func file_bonanza_build_pkg_proto_model_tag_tag_proto_rawDescGZIP() []byte {
	file_bonanza_build_pkg_proto_model_tag_tag_proto_rawDescOnce.Do(func() {
		file_bonanza_build_pkg_proto_model_tag_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_model_tag_tag_proto_rawDesc), len(file_bonanza_build_pkg_proto_model_tag_tag_proto_rawDesc)))
	})
	return file_bonanza_build_pkg_proto_model_tag_tag_proto_rawDescData
}

var file_bonanza_build_pkg_proto_model_tag_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bonanza_build_pkg_proto_model_tag_tag_proto_goTypes = []any{
	(*CommonKeyData)(nil),             // 0: bonanza.model.tag.CommonKeyData
	(object.ReferenceFormat_Value)(0), // 1: bonanza.storage.object.ReferenceFormat.Value
	(*encoding.BinaryEncoder)(nil),    // 2: bonanza.model.encoding.BinaryEncoder
}
var file_bonanza_build_pkg_proto_model_tag_tag_proto_depIdxs = []int32{
	1, // 0: bonanza.model.tag.CommonKeyData.reference_format:type_name -> bonanza.storage.object.ReferenceFormat.Value
	2, // 1: bonanza.model.tag.CommonKeyData.object_encoders:type_name -> bonanza.model.encoding.BinaryEncoder
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bonanza_build_pkg_proto_model_tag_tag_proto_init() }
func file_bonanza_build_pkg_proto_model_tag_tag_proto_init() {
	if File_bonanza_build_pkg_proto_model_tag_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_model_tag_tag_proto_rawDesc), len(file_bonanza_build_pkg_proto_model_tag_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bonanza_build_pkg_proto_model_tag_tag_proto_goTypes,
		DependencyIndexes: file_bonanza_build_pkg_proto_model_tag_tag_proto_depIdxs,
		MessageInfos:      file_bonanza_build_pkg_proto_model_tag_tag_proto_msgTypes,
	}.Build()
	File_bonanza_build_pkg_proto_model_tag_tag_proto = out.File
	file_bonanza_build_pkg_proto_model_tag_tag_proto_goTypes = nil
	file_bonanza_build_pkg_proto_model_tag_tag_proto_depIdxs = nil
}
